# Snakefile
#===============================================================================
# Generate N=300 genotypes for G in {5, 10, 30} from an Ising model.
# Off-diagonal entries are sampled from a spike-and-slab prior (80% zero entries,
# otherwise drawn from Normal(0, 5^2)), and diagonal entries are drawn from
# Normal(0, 5^2).
#===============================================================================

import os
import sys
from pathlib import Path

import jax
import jax.numpy as jnp
import jax.random as jrandom

# TODO: there's a difference between .venv and conda environment. 
# Figure out how to make conda environment work with whole project imports
from workflow import *
from _sampling import *

# -------------------------
# PARAMETERS
# -------------------------
N_SAMPLES = 300
G_LIST = [5, 10, 30]
RANDOM_SEED = 42
SPIKE_WEIGHT = 0.8
SCALE = 5.0

# -------------------------
# PATHS
# -------------------------
OUTPUT_DIR = Path("data")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# -------------------------
# Snakemake Rules
# -------------------------

rule all:
    input:
        expand(f"{OUTPUT_DIR}/G_{{g}}/genotypes.npy", g=G_LIST),
        expand(f"{OUTPUT_DIR}/G_{{g}}/weights.npy", g=G_LIST)

rule sample_ising_model:
    output:
        weights = f"{OUTPUT_DIR}/G_{{g}}/weights.npy"
    params:
        spike_weight=SPIKE_WEIGHT,
        scale=SCALE
    run:
        key = jrandom.PRNGKey(RANDOM_SEED)
        g = int(wildcards.g)
        os.makedirs(f"{OUTPUT_DIR}/G_{g}", exist_ok=True)
        
        mat = sample_ising_model_matrix(
            key, 
            g, 
            p_zero=params.spike_weight, 
            scale=params.scale
        )
        jnp.save(output.weights, mat)

rule exact_sample_ising:
    input:
        interaction_matrix = f"{OUTPUT_DIR}/G_{{g}}/weights.npy"
    output:
        genotypes = f"{OUTPUT_DIR}/G_{{g}}/genotypes.npy"
    params:
        n_samples=N_SAMPLES
    run:
        g = int(wildcards.g)
        if g <= 10: 
          key = jrandom.PRNGKey(RANDOM_SEED)
          mat = jnp.load(input.interaction_matrix)
          energy_fn = unnorm_log_prob_ising_model(mat)
          samples = categorical_exact_sampling(key,  params.n_samples, g, energy_fn )
          jnp.save(output.genotypes, samples)
        else:
          mat = jnp.load(input.interaction_matrix)
          jnp.save(output.genotypes, mat)
